import type { Hotel } from './types';

export const mockHotels: Hotel[] = [
  {
    id: 1,
    name: 'Nicolas Luxury Suites',
    nameEn: 'Nicolas Luxury Suites',
    location: 'Bogotá',
    locationEn: 'Bogota',
    price: 1000000,
    rating: 4.9,
    image: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Suites de lujo en el corazón de Bogotá con comodidades modernas y vistas panorámicas.',
    descriptionEn: 'Luxury suites in the heart of Bogota with modern amenities and panoramic views.',
    amenities: ['WiFi', 'Piscina', 'Gimnasio', 'Spa', 'Restaurante']
  },
  {
    id: 2,
    name: 'Casa Deco Hotel',
    nameEn: 'Casa Deco Hotel',
    location: 'Bogotá',
    locationEn: 'Bogota',
    price: 850000,
    rating: 4.8,
    image: 'https://images.pexels.com/photos/262047/pexels-photo-262047.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel boutique en el centro histórico de Bogotá, con diseño contemporáneo y arte local.',
    descriptionEn: 'Boutique hotel in the historic center of Bogota with contemporary design and local art.',
    amenities: ['WiFi', 'Desayuno', 'Bar', 'Terraza']
  },
  {
    id: 3,
    name: 'Hotel de la Opera',
    nameEn: 'Opera Hotel',
    location: 'Bogotá',
    locationEn: 'Bogota',
    price: 1200000,
    rating: 4.7,
    image: 'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel de lujo en el centro de Bogotá, cercano a teatros y restaurantes.',
    descriptionEn: 'Luxury hotel in downtown Bogota near theaters and restaurants.',
    amenities: ['WiFi', 'Piscina', 'Spa', 'Concierge']
  },
  {
    id: 4,
    name: 'Diez Hotel',
    nameEn: 'Diez Hotel',
    location: 'Medellín',
    locationEn: 'Medellin',
    price: 720000,
    rating: 4.6,
    image: 'https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel moderno en el corazón de Medellín, con diseño innovador y vistas a la ciudad.',
    descriptionEn: 'Modern hotel in the heart of Medellin with innovative design and city views.',
    amenities: ['WiFi', 'Desayuno', 'Piscina', 'Bar']
  },
  {
    id: 5,
    name: 'Hotel Poblado Plaza',
    nameEn: 'Poblado Plaza Hotel',
    location: 'Medellín',
    locationEn: 'Medellin',
    price: 650000,
    rating: 4.5,
    image: 'https://images.pexels.com/photos/260931/pexels-photo-260931.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel cómodo en el barrio El Poblado, ideal para negocios y turismo.',
    descriptionEn: 'Comfortable hotel in El Poblado neighborhood, ideal for business and tourism.',
    amenities: ['WiFi', 'Estacionamiento', 'Gimnasio', 'Restaurante']
  },
  {
    id: 6,
    name: 'Sofitel Legend Santa Clara',
    nameEn: 'Sofitel Legend Santa Clara',
    location: 'Cartagena',
    locationEn: 'Cartagena',
    price: 1500000,
    rating: 4.9,
    image: 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel histórico de lujo en Cartagena, con arquitectura colonial y spa exclusivo.',
    descriptionEn: 'Historic luxury hotel in Cartagena with colonial architecture and an exclusive spa.',
    amenities: ['WiFi', 'Piscina', 'Spa', 'Acceso a playa', 'Restaurante']
  },
  {
    id: 7,
    name: 'Hotel Santa Clara',
    nameEn: 'Santa Clara Hotel',
    location: 'Cartagena',
    locationEn: 'Cartagena',
    price: 880000,
    rating: 4.7,
    image: 'https://images.pexels.com/photos/261169/pexels-photo-261169.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Convento convertido en hotel boutique en el centro histórico de Cartagena.',
    descriptionEn: 'Convent transformed into a boutique hotel in Cartagena historic center.',
    amenities: ['WiFi', 'Piscina', 'Patio', 'Bar']
  },
  {
    id: 8,
    name: 'InterContinental Cali',
    nameEn: 'InterContinental Cali',
    location: 'Cali',
    locationEn: 'Cali',
    price: 480000,
    rating: 4.4,
    image: 'https://images.pexels.com/photos/2869215/pexels-photo-2869215.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel de negocios en Cali, con instalaciones modernas y servicio de alta calidad.',
    descriptionEn: 'Business hotel in Cali with modern facilities and high-quality service.',
    amenities: ['WiFi', 'Piscina', 'Gimnasio', 'Restaurante']
  },
  {
    id: 9,
    name: 'Hotel Dann Carlton',
    nameEn: 'Dann Carlton Hotel',
    location: 'Cali',
    locationEn: 'Cali',
    price: 550000,
    rating: 4.3,
    image: 'https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel tradicional en el centro de Cali, con historia y comodidad.',
    descriptionEn: 'Traditional hotel in downtown Cali with history and comfort.',
    amenities: ['WiFi', 'Desayuno', 'Bar', 'Estacionamiento']
  },
  {
    id: 10,
    name: 'Hotel El Prado',
    nameEn: 'El Prado Hotel',
    location: 'Barranquilla',
    locationEn: 'Barranquilla',
    price: 640000,
    rating: 4.4,
    image: 'https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel icónico en Barranquilla, con arquitectura art deco y encanto histórico.',
    descriptionEn: 'Iconic hotel in Barranquilla with art deco architecture and historic charm.',
    amenities: ['WiFi', 'Piscina', 'Restaurante', 'Bar']
  },
  {
    id: 11,
    name: 'Hotel Casa Deco Bucaramanga',
    nameEn: 'Casa Deco Bucaramanga Hotel',
    location: 'Bucaramanga',
    locationEn: 'Bucaramanga',
    price: 560000,
    rating: 4.3,
    image: 'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel boutique en Bucaramanga, con diseño elegante y vistas a las montañas.',
    descriptionEn: 'Boutique hotel in Bucaramanga with elegant design and mountain views.',
    amenities: ['WiFi', 'Desayuno', 'Terraza', 'Senderismo']
  },
  {
    id: 12,
    name: 'Hotel Movich Pereira',
    nameEn: 'Movich Pereira Hotel',
    location: 'Pereira',
    locationEn: 'Pereira',
    price: 520000,
    rating: 4.1,
    image: 'https://images.pexels.com/photos/261187/pexels-photo-261187.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel moderno en Pereira, en el eje cafetero, con comodidades para viajeros.',
    descriptionEn: 'Modern hotel in Pereira, in the coffee region, with traveler-friendly amenities.',
    amenities: ['WiFi', 'Desayuno', 'Gimnasio', 'Guías turísticos']
  },
  {
    id: 13,
    name: 'Hotel Irotama Resort',
    nameEn: 'Irotama Resort Hotel',
    location: 'Santa Marta',
    locationEn: 'Santa Marta',
    price: 760000,
    rating: 4.5,
    image: 'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Resort en Santa Marta, cerca del Parque Tayrona, con playas privadas.',
    descriptionEn: 'Resort in Santa Marta near Tayrona Park with private beaches.',
    amenities: ['WiFi', 'Piscina', 'Acceso a playa', 'Spa']
  },
  {
    id: 14,
    name: 'Hotel Estelar La Fontana',
    nameEn: 'Estelar La Fontana Hotel',
    location: 'Armenia',
    locationEn: 'Armenia',
    price: 450000,
    rating: 4.2,
    image: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel en Armenia, en el Quindío, con jardines y cafeterías cercanas.',
    descriptionEn: 'Hotel in Armenia, Quindio, with gardens and nearby coffee shops.',
    amenities: ['WiFi', 'Desayuno', 'Piscina', 'Jardín']
  },
  {
    id: 15,
    name: 'Hotel Hacienda Venecia',
    nameEn: 'Hacienda Venecia Hotel',
    location: 'Salento',
    locationEn: 'Salento',
    price: 600000,
    rating: 4.6,
    image: 'https://images.pexels.com/photos/2736388/pexels-photo-2736388.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hacienda colonial en Salento, ideal para turismo rural y naturaleza.',
    descriptionEn: 'Colonial hacienda in Salento, ideal for rural tourism and nature.',
    amenities: ['WiFi', 'Desayuno', 'Cabalgatas', 'Senderismo']
  },
  {
    id: 16,
    name: 'Hotel Charleston Santa Marta',
    nameEn: 'Charleston Santa Marta Hotel',
    location: 'Santa Marta',
    locationEn: 'Santa Marta',
    price: 700000,
    rating: 4.4,
    image: 'https://images.pexels.com/photos/261395/pexels-photo-261395.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel boutique en Santa Marta, con diseño caribeño y piscina infinita.',
    descriptionEn: 'Boutique hotel in Santa Marta with Caribbean design and infinity pool.',
    amenities: ['WiFi', 'Piscina', 'Bar', 'Acceso a playa']
  },
  {
    id: 17,
    name: 'Hotel Casa Deco Armenia',
    nameEn: 'Casa Deco Armenia Hotel',
    location: 'Armenia',
    locationEn: 'Armenia',
    price: 500000,
    rating: 4.3,
    image: 'https://images.pexels.com/photos/261388/pexels-photo-261388.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel moderno en Armenia, con habitaciones cómodas y servicio personalizado.',
    descriptionEn: 'Modern hotel in Armenia with comfortable rooms and personalized service.',
    amenities: ['WiFi', 'Desayuno', 'Estacionamiento', 'Terraza']
  },
  {
    id: 18,
    name: 'Hotel San Antonio Plaza',
    nameEn: 'San Antonio Plaza Hotel',
    location: 'Popayán',
    locationEn: 'Popayan',
    price: 400000,
    rating: 4.0,
    image: 'https://images.pexels.com/photos/2096983/pexels-photo-2096983.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel en el centro histórico de Popayán, con arquitectura colonial.',
    descriptionEn: 'Hotel in the historic center of Popayan with colonial architecture.',
    amenities: ['WiFi', 'Desayuno', 'Patio', 'Guías']
  },
  {
    id: 19,
    name: 'Hotel Dann Monasterio',
    nameEn: 'Dann Monasterio Hotel',
    location: 'Cartagena',
    locationEn: 'Cartagena',
    price: 1300000,
    rating: 4.8,
    image: 'https://images.pexels.com/photos/2869232/pexels-photo-2869232.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel de lujo en Cartagena, en un monasterio histórico con spa y piscina.',
    descriptionEn: 'Luxury hotel in Cartagena inside a historic monastery with spa and pool.',
    amenities: ['WiFi', 'Piscina', 'Spa', 'Restaurante', 'Bar']
  },
  {
    id: 20,
    name: 'Hotel Casa Deco Medellín',
    nameEn: 'Casa Deco Medellin Hotel',
    location: 'Medellín',
    locationEn: 'Medellin',
    price: 680000,
    rating: 4.5,
    image: 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    description: 'Hotel boutique en Medellín, con diseño urbano y comodidades modernas.',
    descriptionEn: 'Boutique hotel in Medellin with urban design and modern amenities.',
    amenities: ['WiFi', 'Desayuno', 'Bar', 'Terraza']
  }
]
